//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotDogReview.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establishment
    {
        public Establishment()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsVegan { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string Address { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
